# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ev/Git/drawMech/app/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.sl_scale = QtWidgets.QSlider(self.centralwidget)
        self.sl_scale.setMinimum(1)
        self.sl_scale.setMaximum(100)
        self.sl_scale.setOrientation(QtCore.Qt.Horizontal)
        self.sl_scale.setObjectName("sl_scale")
        self.horizontalLayout_7.addWidget(self.sl_scale)
        self.l_scale = QtWidgets.QLabel(self.centralwidget)
        self.l_scale.setObjectName("l_scale")
        self.horizontalLayout_7.addWidget(self.l_scale)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.graphicsView_A = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_A.setObjectName("graphicsView_A")
        self.verticalLayout_2.addWidget(self.graphicsView_A)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "draw Mech"))
        self.label_7.setText(_translate("MainWindow", "scale:"))
        self.l_scale.setText(_translate("MainWindow", "x 1"))
