name: Github Actions with Qt on macOS

on: push

jobs:
  
  build-and-package-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        run: |
          brew update
          brew install qt@6

      - name: Set up Qt environment
        run: |
          echo 'export PATH=/usr/local/opt/qt@6/bin:$PATH' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Configure Qt project
        run: |
          /usr/local/opt/qt@6/bin/qmake app/app.pro
          echo "qmake completed"

      - name: Build Qt project
        run: |
          make > build_log.txt
          echo "Build log:"
          cat build_log.txt

      - name: Check build output directory
        run: |
          echo "Checking if release directory exists"
          if [ -d "release" ]; then
            echo "Listing release directory"
            ls -la release
          else
            echo "Release directory does not exist"
          fi

      - name: Move files to deploy folder
        run: |
          mkdir -p deploy
          echo "Moving files from release"
          cp -r release/* deploy/

      - name: Deploy Qt application
        run: |
          echo "Deploying application"
          # Add any additional deployment steps if needed

      - name: Create tar.gz archive
        run: tar -czvf application-macos.tar.gz -C deploy .

      - name: Upload tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-macos-tar
          path: application-macos.tar.gz
