name: Github Actions with QT

on: push

jobs:
  
  build-and-package-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
            version: 6.7.0
            host: windows
            target: desktop
            arch: win64_msvc2019_64

      - name: Configure QT project
        run: |
          qmake app/app.pro
          echo "qmake completed"

      - name: Build QT project
        run: |
          nmake > build_log.txt
          echo "Build log:"
          type build_log.txt

      - name: Check build output directory
        run: |
          echo "Checking if release directory exists"
          if (Test-Path -Path "release") {
            echo "Listing release directory"
            Get-ChildItem -Path "release"
          } else {
            echo "Release directory does not exist"
          }

      - name: Move files to deploy folder
        run: |
          mkdir deploy
          echo "Moving files from release"
          Get-ChildItem -Path "release" -File | Copy-Item -Destination "deploy" -Force -ErrorAction SilentlyContinue
          echo "Moving files from tests\base_test\release"
          Get-ChildItem -Path "tests\base_test\release" -File | Copy-Item -Destination "deploy" -Force -ErrorAction SilentlyContinue
          echo "Moving files from tests\ui_test\release"
          Get-ChildItem -Path "tests\ui_test\release" -File | Copy-Item -Destination "deploy" -Force -ErrorAction SilentlyContinue
          echo "Copying samples directory"
          xcopy /E /I "samples" "deploy\samples\"

      - name: Deploy QT application
        run: |
          windeployqt --release deploy/app.exe
          windeployqt --release deploy/base_test.exe
          windeployqt --release deploy/ui_test.exe

      # - name: Run tests
      #   run: |
      #     cd deploy
      #     ./base_test.exe
      #     ./ui_test.exe

      - name: Create zip archive
        run: 7z a application-windows.zip ./deploy/*

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-windows-zip
          path: application-windows.zip
